### ISSUE TITLE
Maximum XOR problem

### ISSUE THREAD

**Issue by notlmn** [harshatech/competitive-programming#1]
# Maximum XOR
Given an array of positive integers, find 2 elements such that their xor: a ^ b is maximum.

## Input Format

First line of input contains T - number of test cases. Its followed by 2T lines - the first line contains N: the size of the array. The second line contains N integers - the elements of the array.

## Constraints

- 50 points 
  - 1 <= T <= 100 
  - 2 <= N <= 103 
  - 0 <= A[i] <= 106 

- 150 points 
  - 1 <= T <= 100 
  - 2 <= N <= 105 
  - 0 <= A[i] <= 106 

## Output Format

For each test case, print the value of the maximum xor, separated by new line.

## Sample Input 0
```
2
3
12 15 9 
5
13 11 35 3 32 
```
## Sample Output 0
```
6
46
```
### Test Case 1
You can form the following xor pairs: 
12^15 = 3, 12^9 = 5, 15^9 = 6 : max = 6

**Comment by abhiy13** [comment]
Working on It

**Comment by vardhanrao** [comment]
@AbhiY98 you should have also written the readme.md file

**Comment by abhiy13** [comment]
Will do that ASAP @harshatech
