### ISSUE TITLE
Compute a power b

### ISSUE THREAD

**Issue by vardhanrao** [harshatech/competitive-programming#2]
# Compute a power b

Given 2 numbers - a and b, evaluate a<sup>b</sup>.

## Input Format

First line of input contains T - number of test cases. Its followed by T lines, each line containing 2 numbers - a and b, separated by space.

## Constraints

- 30 points
  - 1 <= T <= 1000
  - 0 <= a <= 106
  - 0 <= b <= 103

- 70 points
  - 1 <= T <= 1000
  - 0 <= a <= 106
  - 0 <= b <= 109

## Output Format

For each test case, print a<sup>b</sup>, separated by new line. Since the result can be very large, print result % 1000000007

## Sample Input 0

```
4
5 2
1 10
2 30
10 10
```

## Sample Output 0

```
25
1
73741817
999999937
```

**Comment by devikasugathan** [comment]
Done in #22

**Comment by devikasugathan** [comment]
Done in #23

**Comment by vardhanrao** [comment]
@devikasugathan solved this #41
